### ISSUE TITLE
Default instruction in the video player area

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#109]
The default instruction ("What's this....Complete your biodata") in the video player area should be centered (vertically) in mobile portrait mode.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close it.

**Comment by mailanand75** [comment]
The issue is not yet fixed. The content is still not vertically aligned.

**Comment by mailanand75** [comment]
When you fixing this, please change the default instructions to:

"Jodi Logik Minions will create a cool video of your biodata once you complete a few sections below.
<paragraph break>
Complete your biodata now to see your video."

**Comment by mailanand75** [comment]
This issue remains in portrait mode for profile preview mode as well.

**Comment by cyrus-gc** [comment]
Fixed and Please check this in Staging.

**Comment by mailanand75** [comment]
I checked the staging server. Vertical alignment is off in portrait mode. 

See screenshot below. Notice the text group is not vertically aligned (more black space on the top). You can remove the word "cool" in "Check out the cool video we made for your biodata." so that "biodata" doesn't spill over to the third line.

![image](https://cloud.githubusercontent.com/assets/12179089/19142289/f3cd52d2-8bb9-11e6-938c-ca70d508ae71.png)

**Comment by cyrus-gc** [comment]
Fixed.  Please verify this in Staging Server.

**Comment by mailanand75** [comment]
I am waiting for the reactivation email to show up before I can verify the positioning. Will close this as soon as I am able to log in again.

**Comment by mailanand75** [comment]
1. The second line "Check out.....for your biodata." has to be center justified in the portrait mode.
2. In the landscape mode the above line is already center justified. However, you have enough space in the second line to keep "biodada" in the same line instead of making it spill over to the third line.

**Comment by cyrus-gc** [comment]
Fixed. Please check this in Staging.

**Comment by cyrus-gc** [comment]
Please verify and close it.
