### ISSUE TITLE
Devil page issue on mobile devices

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#115]
The devil page shown when the profile owner has disabled access to the biodata doesn't display properly on mobile devices in both portrait and landscape modes.

The header elements -logo and the hamburger icons don't display properly. The message is also not formatted properly.

![image](https://cloud.githubusercontent.com/assets/12179089/18615789/568752c4-7dcd-11e6-87b1-cc50bff61d07.png)

**Comment by cyrus-gc** [comment]
Fixed and Please check this in Staging.

**Comment by mailanand75** [comment]
This is not fixed. The hamburger icon and the logo are not vertically center aligned in the header area.

I also discovered that when I click on the hamburger icon from this page, the menu items are not in white font against the black background. This was partially fixed for the menu items shown after logging into the profile.

**Comment by cyrus-gc** [comment]
Fixed and Please check this in Staging.
