### ISSUE TITLE
Typo in the reactivation notification

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#119]
In the screenshot below, please correct the language "In order to reactive your Jodi Logik profile..." is wrong. The correct version is "In order to reactivate your Jodi Logik account..."

![image](https://cloud.githubusercontent.com/assets/12179089/19157832/360624fe-8c04-11e6-9fe4-798407f135ea.png)

**Comment by cyrus-gc** [comment]
Fixed. Please check this in Staging.

**Comment by mailanand75** [comment]
Not fixed.

![image](https://cloud.githubusercontent.com/assets/12179089/19308144/babb232a-909b-11e6-926e-2a8afaea80f0.png)

**Comment by cyrus-gc** [comment]
Its working fine. Please check now.

**Comment by cyrus-gc** [comment]
Please check this in LIVE and close this.

**Comment by mailanand75** [comment]
I checked the live server. Here is the screenshot. This issue is still pending!

![image](https://cloud.githubusercontent.com/assets/12179089/20453454/ddb92ce6-ae4b-11e6-8a42-0606f61cc45a.png)
