### ISSUE TITLE
Email message for sharing Resources Guide

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#84]
When we use the Share via Email feature for the mens and women's guide, please make sure the default email text is:

"Hello,

Prasanta wants you to check out an interesting guide from Jodi Logik.
To access the guide, click on this link:

The Women's Guide to creating a Biodata for Marriage

If you do not know Prasanta and believe this email was sent to you by mistake, please delete this email or ignore it.

Regards,
Jodi Logik Minions
<remove the line break> 
<hyperlink>Create Cool, Custom Biodata for Marriage<hyperlink to homepage>

**Comment by cyrus-gc** [comment]
Fixed

**Comment by mailanand75** [comment]
Not fixed

![image](https://cloud.githubusercontent.com/assets/12179089/15821070/39638c08-2c0b-11e6-8054-a318bf1aca35.png)

**Comment by cyrus-gc** [comment]
This is not reproducible in staging version. Looks like you have tested LIVE version. Can you please confirm this.
