### ISSUE TITLE
Retrying Join With Facebook button after removing access to email.

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#9]
When I deliberately removed access to email when signing up, the application is asking me to retry. When I retry, I am getting the same message. I am not getting the Facebook API window. The user will never be able to come out of this cycle of click on the Join with Facebook button and seeing the same message over and over again.

**Comment by cyrus-gc** [comment]
Yes, you are right. Ideally the user needs to login to facebook and click on settings --> apps. Here one can find Jodi Logik app. Open this app and select the unselected options. The minimum selected options for a user to join Jodi Logik will be to select email whereas other options will enhance the profile of the user. We can display this sort of message for this scenario instead of the one we have currently. So the message will be like "The email address for this Facebook account is inaccessible. We need the email address to create a matrimony profile in Jodi Logik. Please login to the Facebook account. You can find our Jodi Logik app under settings / apps. Please remove this app. Login to www.jodilogik.com and click on Join with Facebook button." 

Let me know if the above text for the error message is good enough.

**Comment by mailanand75** [comment]
We actualy created a document with screenshots to explain how this is done! I will forward the document.

Here is how we will show the message:

Title: Retain the same title as we have at present
Message: The email address for your Facebook account is inaccessible. We need your email address to create a Jodi Logik profile. Please <hyperlinked>download the instructions<hyperlinked> to reset your Facebook setting and try again."

**Comment by cyrus-gc** [comment]
Thanks for the document. Please do the following changes to the document:
1. In Page 2, do not mark the Jodi Logik page under Your Pages menu. Settings menu is highlighted which is correct.
2. In Page 5, step 4, change it completely. The user needs to "Remove App" link which is at the bottom part of the popup. 
3. In Page 5, we can see your personal details that are SENSITIVE information according to BIS standards. Please mask them. Mask your name, profile picture throughout the document.

Please send us this document after the changes.

**Comment by mailanand75** [comment]
Hi Cyrus, I have updated the document and sent it via email. Can you review and provide inputs the last step to enable access to the email?

**Comment by cyrus-gc** [comment]
Fixed. Please verify.

**Comment by mailanand75** [comment]
I tried again now. This issue is not fixed.

![image](https://cloud.githubusercontent.com/assets/12179089/9882825/48f33a2a-5bf4-11e5-9f47-16a56651a149.png)

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close.
